[[opener.rider]]
run = 'open -a "Rider" %s'
orphan = true
desc = "Open in Rider"
for = "macos"

[[opener.finder]]
run = "open %s"
orphan = true
desc = "Open in Finder"
for = "macos"

[mgr]
show_hidden = true
linemode = "mtime"

[[open.prepend_rules]]
url = "*/"
use = "finder"

[[open.prepend_rules]]
url = "*.{sln,slnx}"
use = "rider"

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
